### ISSUE TITLE
question

### ISSUE THREAD

**Issue by mrc4tt** [Aniket999969/DDoS-alerts#1]
Hi, @Aniket999969 

Do this works? ^ - I mean, would be nice with some "screenshots" =)

**Comment by bugsfixing** [comment]
![IMG_20221006_203236_825](https://user-images.githubusercontent.com/72073185/198985629-cee7a3e8-c167-4d9b-9fb9-83a298e1e381.jpg)
Here is how it looks on discord end.

**Comment by mrc4tt** [comment]
Oh nice, thanks for help! :+1:
