### ISSUE TITLE
Little problem

### ISSUE THREAD

**Issue by mrc4tt** [Aniket999969/DDoS-alerts#2]
Hi,

I got issues with running the script.
Using Ubuntu 22.04
```php
Traceback (most recent call last):
  File "/root/DDoS-alerts-main/mitigation.py", line 46, in <module>
    old_b2 = int(old_b.decode('utf8').rstrip())
ValueError: invalid literal for int() with base 10: '267653031025\n4110949418\n19392039901'
```

**Comment by bugsfixing** [comment]
are you using python3?

**Comment by mrc4tt** [comment]
> are you using python3?

Yep
Python 3.9.2

I have tested on my other server, where it stopped with this error:
```php
Traceback (most recent call last):
  File "mitigation.py", line 252, in <module>
    CPU_Pct=str(round(float(os.popen('''top -n 1 -b | awk '/^%Cpu/{print $2}' ''').readline())))
ValueError: could not convert string to float: '0,0\n'
```

**Comment by bugsfixing** [comment]
Hi 

ive just commited the fix. try now

**Comment by mrc4tt** [comment]
Hi, 

Still the same problem.
```php
Traceback (most recent call last):
  File "/root/DDoS-alerts-main/mitigation.py", line 46, in <module>
    old_b2 = int(float(old_b.decode('utf8').rstrip()))
ValueError: could not convert string to float: '267820462682\n4122258131\n19392041541'
```

**Comment by bugsfixing** [comment]
Thank you! i will fix that in the mean time you can try using older version of python seems to something in newer versions!

**Comment by mrc4tt** [comment]
@Aniket999969 good to know, let me know when it's fixed.
Are you planning to update it so that it can detect `ipsec-nat-t` attack?

**Comment by bugsfixing** [comment]
Sure. I can work on that one. Currently I was busy doing my JNCIA. Almost done with it just exam is left.

**Comment by mrc4tt** [comment]
Any update? ^
